<?php

namespace App\Http\Controllers;

use App\Models\Bcategory;
use App\Models\Bcatergory;
use App\Models\Blog;
use App\Models\Btag;
use App\Models\Prayer;
use Illuminate\Http\Request;

class FrontendController extends Controller
{

    public function callAction($method, $parameters)
    {
        $data['footer_blogs'] = Blog::orderBy('id', 'desc')->limit(3)->get();

        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function index()
    {
        $data['recent_blogs'] = Blog::orderBy('id', 'desc')->limit(3)->get();


        return view('frontend.pages.home', $data);
    }

    public function prayers()
    {
        $data['recent_blogs'] = Blog::orderBy('id', 'desc')->limit(3)->get();
        $data['prayers'] = Prayer::orderBy('id', 'desc')->get();
        return view('frontend.pages.prayers.prayers', $data);
    }

    public function single_prayer()
    {
        $data['recent_blogs'] = Blog::orderBy('id', 'desc')->limit(3)->get();
        return view('frontend.pages.prayers.single-prayer',$data);
    }

    public function contact()
    {
        $data['recent_blogs'] = Blog::orderBy('id', 'desc')->limit(3)->get();
        return view('frontend.pages.contact',$data);
    }

    public function blog()
    {
        $data['recent_blogs'] = Blog::orderBy('id', 'desc')->limit(3)->get();
        $data['blogs'] = Blog::orderBy('id', 'desc')->get();

        return view('frontend.pages.blog.blogs', $data);
    }

    public function blog_category(Bcategory $category)
    {
        $data['recent_blogs'] = Blog::orderBy('id', 'desc')->limit(3)->get();
        $data['category'] = $category;
        return view('frontend.pages.blog.blog-category', $data);
    }

    public function blog_tag(Btag $tag)
    {
        $data['recent_blogs'] = Blog::orderBy('id', 'desc')->limit(3)->get();
        $data['tag'] = $tag;
        return view('frontend.pages.blog.blog-tag', $data);
    }

    public function single_blog_page( $blog)
    {


        $data['blog'] = Blog::where('codename', $blog)->first();
        if (!$data['blog']) {
            $data['blog'] = Blog::find($blog);
        }
        if (!$data['blog']) {
            return redirect()->route('home', app()->getLocale());
        }
        $data['blog']->views = $data['blog']->views + 1;
        $data['blog']->save();

        $data['recent_blogs'] = Blog::orderBy('id', 'desc')->limit(3)->get();


        $data['categories'] = Bcategory::inRandomOrder()->limit(6)->get();
        $data['tags'] = Btag::inRandomOrder()->limit(5)->get();
        $data['next_blog'] = Blog::orderBy('id', 'desc')->where('id', '!=', $data['blog']->id)->first();
        $data['prec_blog'] = Blog::orderBy('id', 'desc')->where('id', '!=', $data['blog']->id)->where('id', '!=', $data['next_blog']->id)->first();

        return view('frontend.pages.blog.single-blog', $data);
    }
}
